# Generated by Django 3.2.6 on 2021-08-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Email',
            field=models.EmailField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Mobileno',
            field=models.CharField(default='', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='add',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='village',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
